kind: Deployment
apiVersion: apps/v1
metadata:
  name: recipe-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-backend-api
  template:
    metadata:
      labels:
        app: recipe-backend-api
    spec:
      containers:
        - name: recipe-backend-api
          image: ezechima123/recipe-backend-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8654
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8654
#            initialDelaySeconds: 5
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: recipe-backend-api
spec:
  type: NodePort
  ports:
    - port: 8654
      targetPort: 8654
      protocol: TCP
      nodePort: 31000
  selector:
    app: recipe-backend-api