version: '3.8'
services:
  mongo:
    container_name: myapp-mongo
    image: 'mongo'
    restart: unless-stopped
    ports:
      - '27017:27017'
      
  redis:
    container_name: myapp-redis
    image: 'redis/redis-stack'
    restart: unless-stopped
    ports:
      - '6379:6379'
    depends_on:
      - mongo